import type { Listing } from '@/components/listing/ListingCard'
import type { Worker } from '@/components/worker/WorkerCard'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: '2BHK Furnished Flat in Paltan Bazar',
    locality: 'Paltan Bazar, Guwahati',
    rent: 14000,
    deposit: 28000,
    bhk: 2,
    areaSqft: 850,
    floor: 3,
    furnishing: 'Furnished',
    propertyType: 'Flat',
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80',
    ],
    isVerified: true,
    isPopular: true,
    owner: { name: 'Ranjit Bora', verified: true },
    isLocked: true,
  },
  {
    id: '2',
    title: '1BHK Semi-furnished near GMCH',
    locality: 'Bhangagarh, Guwahati',
    rent: 8500,
    deposit: 17000,
    bhk: 1,
    areaSqft: 520,
    floor: 1,
    furnishing: 'Semi-furnished',
    propertyType: 'Flat',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80',
    ],
    isVerified: true,
    owner: { name: 'Priya Sarma', verified: false },
    isLocked: true,
  },
  {
    id: '3',
    title: 'Spacious 3BHK House with Parking',
    locality: 'Zoo Road, Guwahati',
    rent: 22000,
    deposit: 44000,
    bhk: 3,
    areaSqft: 1400,
    floor: 0,
    furnishing: 'Unfurnished',
    propertyType: 'House',
    photos: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80',
    ],
    isVerified: false,
    isBoosted: true,
    owner: { name: 'Dilip Nath', verified: true },
    isLocked: true,
  },
  {
    id: '4',
    title: 'Girls PG near Cotton University',
    locality: 'Panbazar, Guwahati',
    rent: 5500,
    deposit: 5500,
    furnishing: 'Furnished',
    propertyType: 'PG',
    photos: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
    ],
    isVerified: true,
    isPopular: true,
    owner: { name: 'Anita Devi', verified: true },
    isLocked: false,
  },
  {
    id: '5',
    title: 'Studio Room Near IT Park',
    locality: 'Basistha, Guwahati',
    rent: 6000,
    deposit: 12000,
    areaSqft: 320,
    floor: 2,
    furnishing: 'Semi-furnished',
    propertyType: 'Room',
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80',
    ],
    isVerified: false,
    owner: { name: 'Kamal Das', verified: false },
    isLocked: true,
  },
  {
    id: '6',
    title: '2BHK Flat with Rooftop Access',
    locality: 'Rehabari, Guwahati',
    rent: 11000,
    deposit: 22000,
    bhk: 2,
    areaSqft: 780,
    floor: 4,
    furnishing: 'Semi-furnished',
    propertyType: 'Flat',
    photos: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80',
    ],
    isVerified: true,
    owner: { name: 'Mridul Hazarika', verified: true },
    isLocked: true,
  },
]

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'w1',
    name: 'Bipul Kalita',
    category: 'Electrician',
    skills: ['Wiring', 'AC Installation', 'MCB Fixing', 'Fan Installation'],
    localities: ['Paltan Bazar', 'Fancy Bazar', 'Panbazar'],
    hourlyRate: 350,
    ratingAvg: 4.8,
    ratingCount: 64,
    jobsCompleted: 120,
    isVerified: true,
    isAvailableToday: true,
  },
  {
    id: 'w2',
    name: 'Rahim Ali',
    category: 'Plumber',
    skills: ['Pipe Fitting', 'Water Heater', 'Bathroom Fitting', 'Leak Repair'],
    localities: ['Bhangagarh', 'Zoo Road', 'Ulubari'],
    hourlyRate: 300,
    ratingAvg: 4.6,
    ratingCount: 42,
    jobsCompleted: 88,
    isVerified: true,
    isAvailableToday: false,
  },
  {
    id: 'w3',
    name: 'Sunita Borah',
    category: 'Cleaner',
    skills: ['Deep Cleaning', 'Kitchen Cleaning', 'Bathroom Cleaning', 'Post-renovation'],
    localities: ['Basistha', 'Rehabari', 'Hatigaon'],
    hourlyRate: 200,
    ratingAvg: 4.9,
    ratingCount: 91,
    jobsCompleted: 200,
    isVerified: true,
    isAvailableToday: true,
  },
  {
    id: 'w4',
    name: 'Manoj Sharma',
    category: 'Carpenter',
    skills: ['Furniture Assembly', 'Door Fitting', 'Cupboard Repair'],
    localities: ['Paltan Bazar', 'Silpukhuri'],
    hourlyRate: 400,
    ratingAvg: 4.5,
    ratingCount: 28,
    jobsCompleted: 55,
    isVerified: false,
    isAvailableToday: true,
  },
  {
    id: 'w5',
    name: 'Dipankar Gogoi',
    category: 'Painter',
    skills: ['Interior Painting', 'Exterior Painting', 'Putty Work', 'Texture Paint'],
    localities: ['Ganeshguri', 'Six Mile', 'Beltola'],
    hourlyRate: 450,
    ratingAvg: 4.7,
    ratingCount: 37,
    jobsCompleted: 72,
    isVerified: true,
    isAvailableToday: true,
  },
]

export const FURNITURE_CATEGORIES = [
  { id: 'refrigerator', name: 'Refrigerator', icon: '🧊', startingPrice: 499, image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&q=80' },
  { id: 'bed', name: 'Bed', icon: '🛏', startingPrice: 399, image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80' },
  { id: 'sofa', name: 'Sofa', icon: '🛋', startingPrice: 599, image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80' },
  { id: 'washing-machine', name: 'Washing Machine', icon: '🫧', startingPrice: 699, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80' },
  { id: 'wardrobe', name: 'Wardrobe', icon: '🗄', startingPrice: 349, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80' },
  { id: 'dining-table', name: 'Dining Table', icon: '🍽', startingPrice: 449, image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400&q=80' },
  { id: 'tv', name: 'Television', icon: '📺', startingPrice: 799, image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&q=80' },
  { id: 'air-cooler', name: 'Air Cooler', icon: '❄', startingPrice: 299, image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80' },
]
